// Photographer-facing inbox messages — generated by admin actions on the
// payouts queue (hold, report acknowledge, report resolve). Surface lives
// in the SiteHeader bell + PhotographerInboxModal. Mock-only; backend wires
// in Phase F via `/me/photographer/messages` + WebSocket for live unread
// count. Mirror of the admin-dispute-store pattern: seed + submissions
// (append-only) + overrides (sparse patches for `readAt` flips).

export type PhotographerMessageKind =
  | "payout_held"
  | "report_acknowledged"
  | "report_resolved";

export interface PhotographerMessage {
  id: string;
  /** Recipient — matches AdminPayoutCycle.photographerId. */
  photographerId: string;
  kind: PhotographerMessageKind;
  title: string;
  body: string;
  payoutCycleId?: string;
  reportId?: string;
  createdAt: string;
  readAt: string | null;
  /**
   * Soft-delete flag. Photographer-removed messages stay in the seed array
   * but are hidden from getEffectiveMessages so seed-vs-submission storage
   * stays uniform. Real backend (Phase F) hard-deletes server-side.
   */
  removed?: boolean;
}

export const MESSAGE_KIND_LABEL: Record<PhotographerMessageKind, string> = {
  payout_held: "Payout held",
  report_acknowledged: "Report acknowledged",
  report_resolved: "Report resolved",
};

// Seeded messages so a fresh photographer session has something to look at
// in the inbox before any admin action lands. Tied to the held cycle in
// ADMIN_PAYOUT_SEED so the View-cycle deeplink resolves.
export const PHOTOGRAPHER_MESSAGES: ReadonlyArray<PhotographerMessage> = [
  {
    id: "msg-seed-001",
    photographerId: "photog-cebustride",
    kind: "payout_held",
    title: "Payout held — review pending",
    body:
      "Chargeback rate elevated this cycle — Reviewing card transactions for the week. Payout resumes once cleared.",
    payoutCycleId: "PAY-2026W15-CEBUSTRIDE",
    createdAt: "2026-04-14T11:15:00.000Z",
    readAt: null,
  },
];

export function mergeMessage(
  base: PhotographerMessage,
  patch: Partial<PhotographerMessage> | undefined,
): PhotographerMessage {
  return patch ? { ...base, ...patch } : base;
}

export function getEffectiveMessages(
  submissions: ReadonlyArray<PhotographerMessage>,
  overrides: Record<string, Partial<PhotographerMessage>>,
): PhotographerMessage[] {
  const seed = PHOTOGRAPHER_MESSAGES.map((m) => mergeMessage(m, overrides[m.id]));
  const submitted = submissions.map((m) => mergeMessage(m, overrides[m.id]));
  return [...submitted, ...seed].filter((m) => !m.removed);
}

export function getUnreadCount(
  messages: ReadonlyArray<PhotographerMessage>,
  photographerId: string,
): number {
  let n = 0;
  for (const m of messages) {
    if (m.photographerId === photographerId && m.readAt === null) n += 1;
  }
  return n;
}
