package com.quickpitik.common

object ErrorCodes {
    const val UNAUTHORIZED = "UNAUTHORIZED"
    const val INVALID_TOKEN = "INVALID_TOKEN"
    const val INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    const val INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    const val FORBIDDEN = "FORBIDDEN"
    const val CONFLICT = "CONFLICT"
    const val VALIDATION_ERROR = "VALIDATION_ERROR"
    const val VALIDATION_FAILED = "VALIDATION_FAILED"
    const val INTERNAL_ERROR = "INTERNAL_ERROR"
    const val NOT_FOUND = "NOT_FOUND"

    const val EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    const val EVENT_ARCHIVED = "EVENT_ARCHIVED"
    const val EVENT_NOT_UPLOADABLE = "EVENT_NOT_UPLOADABLE"

    const val PHOTO_NOT_FOUND = "PHOTO_NOT_FOUND"
    const val SELFIE_REQUIRED = "SELFIE_REQUIRED"
    const val SELFIE_REJECTED = "SELFIE_REJECTED"
    const val SELFIE_NOT_FOUND = "SELFIE_NOT_FOUND"
    const val SELFIE_LIMIT_REACHED = "SELFIE_LIMIT_REACHED"
    const val SAME_PASSWORD = "SAME_PASSWORD"
    const val LOW_CONFIDENCE = "LOW_CONFIDENCE"
    const val BLUR_REJECTED = "BLUR_REJECTED"

    const val CART_ITEM_PRICE_CHANGED = "CART_ITEM_PRICE_CHANGED"
    const val ORDER_DUPLICATE_PAYMENT = "ORDER_DUPLICATE_PAYMENT"
    const val ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    const val PAYMENT_FAILED = "PAYMENT_FAILED"
    const val INVALID_IDEMPOTENCY_KEY = "INVALID_IDEMPOTENCY_KEY"

    const val PHOTOGRAPHER_NOT_VERIFIED = "PHOTOGRAPHER_NOT_VERIFIED"
    const val INCOMPLETE_PROFILE = "INCOMPLETE_PROFILE"
    const val RESERVED_HANDLE = "RESERVED_HANDLE"
    const val HANDLE_TAKEN = "HANDLE_TAKEN"
    const val INVALID_REGION = "INVALID_REGION"
    const val INVALID_SOCIAL_URL = "INVALID_SOCIAL_URL"

    const val PAYOUT_NOT_FOUND = "PAYOUT_NOT_FOUND"
    const val REPORT_ALREADY_OPEN = "REPORT_ALREADY_OPEN"
    const val INVALID_REASON = "INVALID_REASON"
    const val MISSING_PAYMENT_REFERENCE = "MISSING_PAYMENT_REFERENCE"
    const val REFUND_AMOUNT_REQUIRED = "REFUND_AMOUNT_REQUIRED"

    const val DISPUTE_NOT_FOUND = "DISPUTE_NOT_FOUND"
    const val INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"

    const val RATE_LIMITED = "RATE_LIMITED"
    const val PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    const val UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"

    const val AI_API_UNAVAILABLE = "AI_API_UNAVAILABLE"
}
