package com.quickpitik.common

object ErrorCodes {
    const val UNAUTHORIZED = "UNAUTHORIZED"
    const val INVALID_TOKEN = "INVALID_TOKEN"
    const val INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    const val INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    const val FORBIDDEN = "FORBIDDEN"
    const val CONFLICT = "CONFLICT"
    const val VALIDATION_ERROR = "VALIDATION_ERROR"
    const val VALIDATION_FAILED = "VALIDATION_FAILED"
    const val INTERNAL_ERROR = "INTERNAL_ERROR"
    const val NOT_FOUND = "NOT_FOUND"
    const val METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"

    const val EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    const val EVENT_ARCHIVED = "EVENT_ARCHIVED"
    const val EVENT_NOT_UPLOADABLE = "EVENT_NOT_UPLOADABLE"

    const val PHOTO_NOT_FOUND = "PHOTO_NOT_FOUND"
    const val PHOTO_DUPLICATE_SAME_EVENT = "PHOTO_DUPLICATE_SAME_EVENT"
    // Direct-to-storage upload (2026-09-02): commit named an object that
    // isn't in storage (PUT never happened or expired), or a key that doesn't
    // belong to the photo id issued at begin.
    const val UPLOAD_OBJECT_MISSING = "UPLOAD_OBJECT_MISSING"
    const val UPLOAD_KEY_MISMATCH = "UPLOAD_KEY_MISMATCH"
    const val PHOTO_DUPLICATE_DIFFERENT_EVENT = "PHOTO_DUPLICATE_DIFFERENT_EVENT"
    const val SELFIE_REQUIRED = "SELFIE_REQUIRED"
    const val SELFIE_REJECTED = "SELFIE_REJECTED"
    const val SELFIE_NOT_FOUND = "SELFIE_NOT_FOUND"
    const val SELFIE_LIMIT_REACHED = "SELFIE_LIMIT_REACHED"
    const val SAME_PASSWORD = "SAME_PASSWORD"
    const val WEAK_PASSWORD = "WEAK_PASSWORD"
    const val EMAIL_TAKEN = "EMAIL_TAKEN"
    const val SAME_EMAIL = "SAME_EMAIL"
    const val INVALID_EMAIL_CHANGE_TOKEN = "INVALID_EMAIL_CHANGE_TOKEN"
    const val INVALID_VERIFICATION_TOKEN = "INVALID_VERIFICATION_TOKEN"
    const val INVALID_RESET_CODE = "INVALID_RESET_CODE"
    const val INVALID_RESET_TOKEN = "INVALID_RESET_TOKEN"
    const val EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED"
    // Google sign-in (V38). ROLE_REQUIRED (422) is the "new Google user, pick
    // RUNNER/PHOTOGRAPHER first" signal both clients branch on.
    const val ROLE_REQUIRED = "ROLE_REQUIRED"
    const val INVALID_GOOGLE_TOKEN = "INVALID_GOOGLE_TOKEN"
    const val GOOGLE_EMAIL_UNVERIFIED = "GOOGLE_EMAIL_UNVERIFIED"
    const val GOOGLE_AUTH_UNAVAILABLE = "GOOGLE_AUTH_UNAVAILABLE"
    const val LOW_CONFIDENCE = "LOW_CONFIDENCE"

    const val CART_ITEM_PRICE_CHANGED = "CART_ITEM_PRICE_CHANGED"
    const val ORDER_DUPLICATE_PAYMENT = "ORDER_DUPLICATE_PAYMENT"
    const val ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    const val PAYMENT_FAILED = "PAYMENT_FAILED"
    const val INVALID_IDEMPOTENCY_KEY = "INVALID_IDEMPOTENCY_KEY"
    const val IDEMPOTENT_REPLAY_IN_PROGRESS = "IDEMPOTENT_REPLAY_IN_PROGRESS"

    const val PHOTOGRAPHER_NOT_VERIFIED = "PHOTOGRAPHER_NOT_VERIFIED"
    const val ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED"
    // Temporary, self-clearing (V29) — unlike ACCOUNT_SUSPENDED, which is an
    // admin decision and only an admin can lift.
    const val ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    const val WATERMARK_MISSING = "WATERMARK_MISSING"
    const val INCOMPLETE_PROFILE = "INCOMPLETE_PROFILE"
    const val RESERVED_HANDLE = "RESERVED_HANDLE"
    const val HANDLE_TAKEN = "HANDLE_TAKEN"
    const val INVALID_REGION = "INVALID_REGION"
    const val INVALID_SOCIAL_URL = "INVALID_SOCIAL_URL"

    const val PAYOUT_NOT_FOUND = "PAYOUT_NOT_FOUND"
    const val REPORT_ALREADY_OPEN = "REPORT_ALREADY_OPEN"
    const val INVALID_REASON = "INVALID_REASON"
    const val MISSING_PAYMENT_REFERENCE = "MISSING_PAYMENT_REFERENCE"
    const val REFUND_AMOUNT_REQUIRED = "REFUND_AMOUNT_REQUIRED"
    const val PAYOUT_REQUEST_OPEN = "PAYOUT_REQUEST_OPEN"
    const val PAYOUT_BELOW_MINIMUM = "PAYOUT_BELOW_MINIMUM"
    const val PAYOUT_NO_ACCOUNT = "PAYOUT_NO_ACCOUNT"

    const val DISPUTE_NOT_FOUND = "DISPUTE_NOT_FOUND"
    const val INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"

    const val USER_NOT_FOUND = "USER_NOT_FOUND"
    const val INVALID_RESOLUTION = "INVALID_RESOLUTION"
    const val INVALID_BULK_ACTION = "INVALID_BULK_ACTION"
    const val FLAGS_DISABLED = "FLAGS_DISABLED"
    const val FLAG_NOT_FOUND = "FLAG_NOT_FOUND"
    const val REPORT_NOT_FOUND = "REPORT_NOT_FOUND"

    const val RATE_LIMITED = "RATE_LIMITED"
    const val PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    const val UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"

    const val AI_API_UNAVAILABLE = "AI_API_UNAVAILABLE"
}
