import type { EventDetail } from "@/types/event";

export const MOCK_EVENT_DETAILS: Record<string, EventDetail> = {
  "cebu-marathon-2026": {
    id: "1",
    slug: "cebu-marathon-2026",
    name: "Cebu Marathon 2026",
    date: "2026-04-28",
    location: "SRP Boulevard, Cebu City",
    photoCount: 1240,
    participantCount: 4800,
    status: "ACTIVE",
    description:
      "The biggest road race in Cebu. Twelve thousand starters across four distances, a 4 a.m. gun, and a finish line on the South Road Properties with the sea on your right. We had eighteen photographers spread across the route from CICC to Il Corso, the Mactan bridge climb, and every kilometre marker on the loop back. Photos go up live as the race runs and stay searchable forever.",
    organizerName: "Cebu Marathon Inc.",
    categories: ["Full Marathon", "21K", "10K", "5K"],
    pricePerPhoto: 80,
    bundlePrice: 350,
    bundleSize: 5,
  },
  "mactan-sunset-run-2026": {
    id: "2",
    slug: "mactan-sunset-run-2026",
    name: "Mactan Sunset Run",
    date: "2026-04-26",
    location: "Mactan Channel Bridge",
    photoCount: 612,
    participantCount: 1800,
    status: "ACTIVE",
    description:
      "A late-afternoon 10K and 5K across the Mactan Channel Bridge with the sun dropping behind the Cebu skyline. Our photographers staked out the bridge crest, the seaside turnaround, and the finish line at the Hilton oval. Expect golden-hour light and a few drone shots from the bridge approach.",
    organizerName: "Mactan Runners Club",
    categories: ["10K", "5K"],
    pricePerPhoto: 60,
    bundlePrice: 250,
    bundleSize: 5,
  },
  "srp-half-marathon-2026": {
    id: "3",
    slug: "srp-half-marathon-2026",
    name: "SRP Half-Marathon",
    date: "2026-04-12",
    location: "South Road Properties, Cebu",
    photoCount: 3850,
    participantCount: 2400,
    status: "COMPLETED",
    description:
      "Six laps of the SRP coastal stretch on a closed course, every kilometre photographed. The 21K, 10K, and 5K all share the same start corral, so expect dense start-line shots and cleaner separations after the first turn at Il Corso. All photos are uploaded and ready to search.",
    organizerName: "Cebu Roadrunners",
    categories: ["21K", "10K", "5K"],
    pricePerPhoto: 70,
    bundlePrice: 300,
    bundleSize: 5,
  },
  "sun-run-cebu-2026": {
    id: "4",
    slug: "sun-run-cebu-2026",
    name: "Sun Run Cebu",
    date: "2026-04-05",
    location: "IT Park, Cebu City",
    photoCount: 2120,
    participantCount: 3100,
    status: "COMPLETED",
    description:
      "A flat city run looped through IT Park and Banilad. Big crowd, fast course, and a relentless start that funnels into the corporate stretch. Our team covered the start arch, the 5K turnaround, and the finish chute by the IT Park stage.",
    organizerName: "Sun Run Philippines",
    categories: ["10K", "5K", "3K"],
    pricePerPhoto: 60,
    bundlePrice: 250,
    bundleSize: 5,
  },
  "mactan-coastal-5k-2026": {
    id: "5",
    slug: "mactan-coastal-5k-2026",
    name: "Mactan Coastal 5K",
    date: "2026-03-29",
    location: "Mactan, Lapu-Lapu City",
    photoCount: 980,
    participantCount: 1200,
    status: "COMPLETED",
    description:
      "A short, scenic 5K hugging the Mactan coast. Easy course, a lot of first-timers, and a strong finish-line ribbon. Photos are sorted by waves of one hundred runners so couples and families running together stay grouped.",
    organizerName: "Lapu-Lapu Run Club",
    categories: ["5K", "3K"],
    pricePerPhoto: 50,
  },
  "cebu-night-run-2025": {
    id: "6",
    slug: "cebu-night-run-2025",
    name: "Cebu City Night Run 2025",
    date: "2025-12-14",
    location: "Cebu Business Park",
    photoCount: 4200,
    participantCount: 5600,
    status: "ARCHIVED",
    description:
      "The end-of-year night run through Cebu Business Park. Photos here are archived but still purchasable — search by face or bib and download what you find.",
    organizerName: "Cebu Business Park Association",
    categories: ["10K", "5K", "3K"],
    pricePerPhoto: 50,
    bundlePrice: 200,
    bundleSize: 5,
  },
  "talisay-10k-2025": {
    id: "7",
    slug: "talisay-10k-2025",
    name: "Talisay 10K",
    date: "2025-11-09",
    location: "Talisay City, Cebu",
    photoCount: 1640,
    participantCount: 1900,
    status: "ARCHIVED",
    description:
      "A flat 10K and 5K through Talisay's coastal road. Archived event — photos remain searchable indefinitely.",
    organizerName: "Talisay City Sports Office",
    categories: ["10K", "5K"],
    pricePerPhoto: 50,
  },
  "cordova-bayrun-2025": {
    id: "8",
    slug: "cordova-bayrun-2025",
    name: "Cordova Bay Run",
    date: "2025-10-19",
    location: "Cordova, Cebu",
    photoCount: 720,
    participantCount: 950,
    status: "ARCHIVED",
    description:
      "A small-town 5K and 3K along the Cordova bayfront. Photos archived — still available for search and download.",
    organizerName: "Cordova LGU",
    categories: ["5K", "3K"],
    pricePerPhoto: 40,
  },
};

export function getEventBySlug(slug: string): EventDetail | null {
  return MOCK_EVENT_DETAILS[slug] ?? null;
}
